### ISSUE TITLE
Cannot download any longer

### ISSUE THREAD

**Issue by StormPooper** [catlinman/campdown#6]
I'm guessing Bandcamp have changed something as I can no longer download any albums, including ones I downloaded a couple of days ago.

```python
Traceback (most recent call last):
  File "/usr/bin/campdown", line 11, in <module>
    load_entry_point('campdown==1.47', 'console_scripts', 'campdown')()
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 73, in cli
    downloader.run()
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 203, in run
    album.download() if album.fetch() else False  # Start the download process if fetches succeeded.
  File "/usr/lib/python3.8/site-packages/campdown/album.py", line 224, in fetch
    if track.prepare():
  File "/usr/lib/python3.8/site-packages/campdown/track.py", line 178, in prepare
    if info["file"]:
KeyError: 'file'
```

**Comment by Jack-O-Brian** [comment]
I think what happen, is the request is not getting any data. `info` is an empty dict

Looking at the code/response, I see that it has a json error. 
- `https://realsheogorath.bandcamp.com/album/black-metal-bullshit`: Album to use as a our test case. 
```
req = safe_get("https://realsheogorath.bandcamp.com/album/black-metal-bullshit")
req= (<Response [200]>)
req.json()
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-8-ea8849b3977c> in <module>
----> 1 req.json()
/usr/lib/python3.8/site-packages/requests/models.py in json(self, **kwargs)
896                     # used.
897                     pass
--> 898         return complexjson.loads(self.text, **kwargs)
899
900     @property
/usr/lib/python3.8/site-packages/simplejson/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
523             parse_constant is None and object_pairs_hook is None
524             and not use_decimal and not kw):
--> 525         return _default_decoder.decode(s)
526     if cls is None:
527         cls = JSONDecoder
/usr/lib/python3.8/site-packages/simplejson/decoder.py in decode(self, s, _w, _PY3)
368         if _PY3 and isinstance(s, bytes):
369             s = str(s, self.encoding)
--> 370         obj, end = self.raw_decode(s)
371         end = _w(s, end).end()
372         if end != len(s):
/usr/lib/python3.8/site-packages/simplejson/decoder.py in raw_decode(self, s, idx, _w, _PY3)
398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 3 column 1 (char 6)
```
[req.text's content](https://pastebin.com/xSc1K5CD).
not sure if this can be used to help, but hey I'm throwing it out there.

**Comment by zealsprince** [comment]
Just noticed this yesterday as well. Seems like the URL for the actual file changed. Thanks for reporting this I'll get on it in a bit!

**Comment by zealsprince** [comment]
Fixed via 4b2987f and published to PyPI!

Update via `python3 -m pip install --upgrade campdown` - thanks for reporting the issue!

**Comment by StormPooper** [comment]
@catlinman thanks for the quick response and update, but I'm still getting issues. The example @HawaiinPizza posted works, but I've tried a few others that I've downloaded previously with no luck. Here's one example, I can provide more if required:

```bash
$ campdown https://vikingguitar.bandcamp.com/album/danse-macabre

Detected Bandcamp album.

Viking Guitar Productions - Danse Macabre
Traceback (most recent call last):
  File "/usr/bin/campdown", line 33, in <module>
    sys.exit(load_entry_point('campdown==1.48', 'console_scripts', 'campdown')())
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 73, in cli
    downloader.run()
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 203, in run
    album.download() if album.fetch() else False  # Start the download process if fetches succeeded.
  File "/usr/lib/python3.8/site-packages/campdown/album.py", line 224, in fetch
    if track.prepare():
  File "/usr/lib/python3.8/site-packages/campdown/track.py", line 177, in prepare
    info = json.loads(raw_info)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 1929 (char 1928)
```

**Comment by zealsprince** [comment]
@StormPooper Damn sorry to hear that; I'll give this another detailed check later today or early tomorrow. Going to venture a guess that different pages now have different formats.

If you want, send me an email over at contact@catlinman.com with all the pages you have identified to throw the error. I can then go through those and assure it works! Thanks!

**Comment by StormPooper** [comment]
@catlinman no worries, appreciate you looking into it. I'll get a list together and wing it over to you, thanks.

**Comment by zealsprince** [comment]
@spcified Seems to have fixed the JSON issue for the time being. I'll take a more detailed look at things later and then author a new release. In the meantime you can build from source!

**Comment by StormPooper** [comment]
Can confirm it's working built from source on every URL I've tried so far, thanks @catlinman.

**Comment by davetremblay** [comment]
It works for audio (sometimes), but not for the artwork.
"Failed to download the artwork. Error code 0"

I got this error for some albums:

```
  File "/Users/xxx/anaconda3/bin/campdown", line 10, in <module>
    sys.exit(cli())
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/campdown/__init__.py", line 73, in cli
    downloader.run()
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/campdown/__init__.py", line 203, in run
    album.download() if album.fetch() else False  # Start the download process if fetches succeeded.
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/campdown/album.py", line 224, in fetch
    if track.prepare():
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/campdown/track.py", line 177, in prepare
    info = json.loads(raw_info)
  File "/Users/xxx/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/xxx/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xxx/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 624 (char 623)
```

**Comment by StormPooper** [comment]
I've had it sometimes fail to download individual files (be it artwork or tracks) but re-running again usually fixes it (not always though). I was seeing this behaviour before the latest changes though, so always assumed it was a Bandcamp-side issue.

**Comment by davetremblay** [comment]
After some testing I think it's because of the apostrophe character.`'` might break the program.

**Comment by davetremblay** [comment]
That should be an easy fix.

**Comment by davetremblay** [comment]
Maybe other characters as well, like "/". Should be an easy thing to update the program to take care of such characters.

**Comment by spcified** [comment]
@davetremblay can you provide a URL that reproduces the error? And yes you are right this was a quick fix, for my Problem. This solution will fail if there is a `"` is surrounded by a json element `,{([])}` inside the quoted value or key field.

Will still fail:
`{"key","value",foo"}`

Also I though the Artwork problem was related. If there is no update by Monday, I'll take a look once more. Would be great if everyone could provide URLs for testing.

**Comment by davetremblay** [comment]
OK cool! The artwork works now (most of the times, sometimes it won't), by the way, so I don't know what that was about. Here are a couple of URLs not working at the moment.

https://weaselwalter.bandcamp.com/album/grist

It doesn't crash at the "/" anymore, but it crashes once it hits the unavailable tracks. It should be able to continue even if not all the tracks are available to stream.

https://mattulerywoolgathering.bandcamp.com/album/a-time-and-a-place-2

https://nostrilcaverns.bandcamp.com/album/spontaneous-synaptic-mutations-part-1-2020

https://ambientmanet.bandcamp.com/album/my-demo-n-s

The previous one I'm never able to get the artwork from.

https://hornbill.bandcamp.com/album/im-sad-and-i-dont-know-why

https://not-applicable.bandcamp.com/album/voltage-controlled-parade-music-vol-1

Thanks again!

**Comment by zealsprince** [comment]
Sorry been rather busy recently but I see you've been all handling the problem well on your own.

If a tested and working solution is found please make a pull request! We can all test on the PR's branch to make sure it's working. After that I'll merge into master and make a new release. Thanks again!

**Comment by spcified** [comment]
@davetremblay I created Issues #10 since there are two different reasons for errors.

The first, fixed in #11, is the result of an album having unplayable tracks.
> https://weaselwalter.bandcamp.com/album/grist

The second problem
> https://nostrilcaverns.bandcamp.com/album/spontaneous-synaptic-mutations-part-1-2020
is related to small files, I have to dig a bit to fix this one.

@catlinman why is there a confidence check for the file size? Is there a reason not to just check `size(file_on_client) == headers.content_length`? I checked b3e9798205da33 for clues, but found no further explanation.

**Comment by spcified** [comment]
All downloads completed with #12
links tested:

- https://realsheogorath.bandcamp.com/album/black-metal-bullshit
- https://weaselwalter.bandcamp.com/album/grist
- https://mattulerywoolgathering.bandcamp.com/album/a-time-and-a-place-2
- https://nostrilcaverns.bandcamp.com/album/spontaneous-synaptic-mutations-part-1-2020
- https://ambientmanet.bandcamp.com/album/my-demo-n-s
- https://hornbill.bandcamp.com/album/im-sad-and-i-dont-know-why
- https://not-applicable.bandcamp.com/album/voltage-controlled-parade-music-vol-1

The downloaded file was checked before complete write to disk.

The mentioned json sanitize issue still remains #7 and https://github.com/catlinman/campdown/issues/6#issuecomment-706005998.

@catlinman I found your confidence_check explanation on line 392..394 but I still don't see why the file should be checked like this immediately after the download.

@davetremblay let me know if there are other issues.

**Comment by adocampo** [comment]
I found some albums I cannot download, the error in all of them is the same:
```
Traceback (most recent call last):
  File "/usr/bin/campdown", line 33, in <module>
    sys.exit(load_entry_point('campdown==1.48', 'console_scripts', 'campdown')())
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 73, in cli
    downloader.run()
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 203, in run
    album.download() if album.fetch() else False  # Start the download process if fetches succeeded.
  File "/usr/lib/python3.8/site-packages/campdown/album.py", line 224, in fetch
    if track.prepare():
  File "/usr/lib/python3.8/site-packages/campdown/track.py", line 177, in prepare
    info = json.loads(raw_info)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 560 (char 559)  <---- this column and char varies, but the error is the very same
```

https://adrianvonziegler.bandcamp.com/album/lifeclock
https://adrianvonziegler.bandcamp.com/album/starchaser-2
https://adrianvonziegler.bandcamp.com/album/libertas
https://adrianvonziegler.bandcamp.com/album/moonsong
https://adrianvonziegler.bandcamp.com/album/darkness-eternal
https://adrianvonziegler.bandcamp.com/album/veiled
https://adrianvonziegler.bandcamp.com/album/moondance
https://adrianvonziegler.bandcamp.com/album/the-celtic-collection-ii
https://adrianvonziegler.bandcamp.com/album/the-complete-discography
This artist has more discs which can be downloaded.

https://camerata-mediolanense.bandcamp.com/album/le-vergini-folli-luxus
https://camerata-mediolanense.bandcamp.com/album/le-vergini-folli
https://camerata-mediolanense.bandcamp.com/album/vertute-honor-bellezza-luxus
https://camerata-mediolanense.bandcamp.com/album/vertute-honor-bellezza-2
https://camerata-mediolanense.bandcamp.com/album/musica-reservata
https://camerata-mediolanense.bandcamp.com/album/madrigali
This works: https://camerata-mediolanense.bandcamp.com/album/campo-di-marte

https://allmyfaithlost.bandcamp.com/album/as-youre-vanishing-in-silence-2016-reissue

**Comment by spcified** [comment]
@adocampo there are two PRs pending that fix all mentioned issues so far.

waiting for @catlinman, (I hope you are fine)

**Comment by zealsprince** [comment]
@spcified Whew. Got a bit sidetracked with life and totally forgot about the open PRs. Merged! :)

Going to leave the issue opened until I push out a new release to PyPI

**Comment by spcified** [comment]
Thanks

**Comment by zealsprince** [comment]
Did some testing and this seems to be fixed as of right now! Going to create a new release, close this issue and publish to PyPI. Thanks for the help everyone!
